cls

@ 05,19 say "лл  лл млппл" color "gr+/n"
@ 06,19 say "лл  лл лл   " color "gr+/n"
@ 07,19 say "лл  лл лл   " color "gr+/n"
@ 08,19 say "плммлп плммл" color "gr+/n"

@ 06,32 say "мпм" color "r+/n"
@ 07,32 say "пмп" color "r+/n"

@ 05,36 say "ллм млл ллппл лпллпл млппл" color "b+/n"
@ 06,36 say "ллолнлл ллмм    лл   лл   " color "b+/n"
@ 07,36 say "лл л лл лл      лл   лл   " color "b+/n"
@ 08,36 say "лл   лл ллммл   лл   плммл" color "b+/n"

@ 09,21 say "College Registration System Version 2.0" color "bg/n"
@ 10,29 say "Copyright (C) 1998-1999" color "bg/n"
@ 11,31 say "All Rights Reserved" color "bg/n"

wait
