function main()
scroll()
asaver := savescreen(00,00,24,79)
setcursor(.f.)


** display u **

        @ 08,01 say "л" color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лл" color "gr+/n"
        @ 09,01 say "л " color "gr+/n"
        @ 10,01 say "л " color "gr+/n"
        @ 11,01 say "л " color "gr+/n"
        @ 12,01 say "л " color "gr+/n"
        @ 13,01 say "л " color "gr+/n"
        @ 14,01 say "л " color "gr+/n"
        @ 15,01 say "п " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллл" color "gr+/n"
        @ 09,01 say "лл " color "gr+/n"
        @ 10,01 say "лл " color "gr+/n"
        @ 11,01 say "лл " color "gr+/n"
        @ 12,01 say "лл " color "gr+/n"
        @ 13,01 say "лл " color "gr+/n"
        @ 14,01 say "лл " color "gr+/n"
        @ 15,01 say "лп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллл" color "gr+/n"
        @ 09,01 say "ллл " color "gr+/n"
        @ 10,01 say "ллл " color "gr+/n"
        @ 11,01 say "ллл " color "gr+/n"
        @ 12,01 say "ллл " color "gr+/n"
        @ 13,01 say "ллл " color "gr+/n"
        @ 14,01 say "ллл " color "gr+/n"
        @ 15,01 say "ллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллл" color "gr+/n"
        @ 09,01 say " ллл " color "gr+/n"
        @ 10,01 say " ллл " color "gr+/n"
        @ 11,01 say " ллл " color "gr+/n"
        @ 12,01 say " ллл " color "gr+/n"
        @ 13,01 say " ллл " color "gr+/n"
        @ 14,01 say "лллл " color "gr+/n"
        @ 15,01 say "лллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say " ллллл" color "gr+/n"
        @ 09,01 say "  ллл " color "gr+/n"
        @ 10,01 say "  ллл " color "gr+/n"
        @ 11,01 say "  ллл " color "gr+/n"
        @ 12,01 say "  ллл " color "gr+/n"
        @ 13,01 say "  ллл " color "gr+/n"
        @ 14,01 say " лллл " color "gr+/n"
        @ 15,01 say "ллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "  ллллл" color "gr+/n"
        @ 09,01 say "   ллл " color "gr+/n"
        @ 10,01 say "   ллл " color "gr+/n"
        @ 11,01 say "   ллл " color "gr+/n"
        @ 12,01 say "   ллл " color "gr+/n"
        @ 13,01 say "   ллл " color "gr+/n"
        @ 14,01 say "  лллл " color "gr+/n"
        @ 15,01 say "лллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "   ллллл" color "gr+/n"
        @ 09,01 say "    ллл " color "gr+/n"
        @ 10,01 say "    ллл " color "gr+/n"
        @ 11,01 say "    ллл " color "gr+/n"
        @ 12,01 say "    ллл " color "gr+/n"
        @ 13,01 say "    ллл " color "gr+/n"
        @ 14,01 say "   лллл " color "gr+/n"
        @ 15,01 say "ллллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "л   ллллл" color "gr+/n"
        @ 09,01 say "     ллл " color "gr+/n"
        @ 10,01 say "     ллл " color "gr+/n"
        @ 11,01 say "     ллл " color "gr+/n"
        @ 12,01 say "     ллл " color "gr+/n"
        @ 13,01 say "     ллл " color "gr+/n"
        @ 14,01 say "л   лллл " color "gr+/n"
        @ 15,01 say "лллллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лл   ллллл" color "gr+/n"
        @ 09,01 say "л     ллл " color "gr+/n"
        @ 10,01 say "л     ллл " color "gr+/n"
        @ 11,01 say "л     ллл " color "gr+/n"
        @ 12,01 say "л     ллл " color "gr+/n"
        @ 13,01 say "л     ллл " color "gr+/n"
        @ 14,01 say "лл   лллл " color "gr+/n"
        @ 15,01 say "ллллллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллл   ллллл" color "gr+/n"
        @ 09,01 say "лл     ллл " color "gr+/n"
        @ 10,01 say "лл     ллл " color "gr+/n"
        @ 11,01 say "лл     ллл " color "gr+/n"
        @ 12,01 say "лл     ллл " color "gr+/n"
        @ 13,01 say "лл     ллл " color "gr+/n"
        @ 14,01 say "ллл   лллл " color "gr+/n"
        @ 15,01 say "лллллллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллл   ллллл" color "gr+/n"
        @ 09,01 say "ллл     ллл " color "gr+/n"
        @ 10,01 say "ллл     ллл " color "gr+/n"
        @ 11,01 say "ллл     ллл " color "gr+/n"
        @ 12,01 say "ллл     ллл " color "gr+/n"
        @ 13,01 say "ллл     ллл " color "gr+/n"
        @ 14,01 say "лллл   лллл " color "gr+/n"
        @ 15,01 say "плллллллллп " color "gr+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллл   ллллл" color "gr+/n"
        @ 09,01 say " ллл     ллл " color "gr+/n"
        @ 10,01 say " ллл     ллл " color "gr+/n"
        @ 11,01 say " ллл     ллл " color "gr+/n"
        @ 12,01 say " ллл     ллл " color "gr+/n"
        @ 13,01 say " ллл     ллл " color "gr+/n"
        @ 14,01 say " лллл   лллл " color "gr+/n"
        @ 15,01 say " плллллллллп " color "gr+/n"


        for ncol := 1 to 80
                @ 08,ncol say "ллллл   ллллл" color "gr+/n"
                @ 09,ncol say " ллл     ллл " color "gr+/n"
                @ 10,ncol say " ллл     ллл " color "gr+/n"
                @ 11,ncol say " ллл     ллл " color "gr+/n"
                @ 12,ncol say " ллл     ллл " color "gr+/n"
                @ 13,ncol say " ллл     ллл " color "gr+/n"
                @ 14,ncol say " лллл   лллл " color "gr+/n"
                @ 15,ncol say " плллллллллп " color "gr+/n"

                for nctr := 1 to 10000
                next

                restscreen(08,ncol,15,ncol,asaver)
        next

** end of letter u **


** display letter c **

        @ 08,01 say "м" color "bg+/n"
        @ 09,01 say "л" color "bg+/n"
        @ 10,01 say " " color "bg+/n"
        @ 11,01 say " " color "bg+/n"
        @ 12,01 say " " color "bg+/n"
        @ 13,01 say " " color "bg+/n"
        @ 14,01 say "л" color "bg+/n"
        @ 15,01 say "п" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лм" color "bg+/n"
        @ 09,01 say "лл" color "bg+/n"
        @ 10,01 say "  " color "bg+/n"
        @ 11,01 say "  " color "bg+/n"
        @ 12,01 say "  " color "bg+/n"
        @ 13,01 say "  " color "bg+/n"
        @ 14,01 say "лл" color "bg+/n"
        @ 15,01 say "лп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллм" color "bg+/n"
        @ 09,01 say " лл" color "bg+/n"
        @ 10,01 say "   " color "bg+/n"
        @ 11,01 say "   " color "bg+/n"
        @ 12,01 say "   " color "bg+/n"
        @ 13,01 say "   " color "bg+/n"
        @ 14,01 say " лл" color "bg+/n"
        @ 15,01 say "ллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллм" color "bg+/n"
        @ 09,01 say "  лл" color "bg+/n"
        @ 10,01 say "    " color "bg+/n"
        @ 11,01 say "    " color "bg+/n"
        @ 12,01 say "    " color "bg+/n"
        @ 13,01 say "    " color "bg+/n"
        @ 14,01 say "  лл" color "bg+/n"
        @ 15,01 say "лллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллм" color "bg+/n"
        @ 09,01 say "   лл" color "bg+/n"
        @ 10,01 say "     " color "bg+/n"
        @ 11,01 say "     " color "bg+/n"
        @ 12,01 say "     " color "bg+/n"
        @ 13,01 say "     " color "bg+/n"
        @ 14,01 say "   лл" color "bg+/n"
        @ 15,01 say "ллллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллм" color "bg+/n"
        @ 09,01 say "    лл" color "bg+/n"
        @ 10,01 say "      " color "bg+/n"
        @ 11,01 say "      " color "bg+/n"
        @ 12,01 say "      " color "bg+/n"
        @ 13,01 say "      " color "bg+/n"
        @ 14,01 say "    лл" color "bg+/n"
        @ 15,01 say "лллллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллм" color "bg+/n"
        @ 09,01 say "     лл" color "bg+/n"
        @ 10,01 say "       " color "bg+/n"
        @ 11,01 say "       " color "bg+/n"
        @ 12,01 say "       " color "bg+/n"
        @ 13,01 say "       " color "bg+/n"
        @ 14,01 say "     лл" color "bg+/n"
        @ 15,01 say "ллллллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллм" color "bg+/n"
        @ 09,01 say "      лл" color "bg+/n"
        @ 10,01 say "        " color "bg+/n"
        @ 11,01 say "        " color "bg+/n"
        @ 12,01 say "        " color "bg+/n"
        @ 13,01 say "        " color "bg+/n"
        @ 14,01 say "      лл" color "bg+/n"
        @ 15,01 say "лллллллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллллм" color "bg+/n"
        @ 09,01 say "л      лл" color "bg+/n"
        @ 10,01 say "л        " color "bg+/n"
        @ 11,01 say "л        " color "bg+/n"
        @ 12,01 say "л        " color "bg+/n"
        @ 13,01 say "л        " color "bg+/n"
        @ 14,01 say "л      лл" color "bg+/n"
        @ 15,01 say "ллллллллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллллм" color "bg+/n"
        @ 09,01 say "лл      лл" color "bg+/n"
        @ 10,01 say "лл        " color "bg+/n"
        @ 11,01 say "лл        " color "bg+/n"
        @ 12,01 say "лл        " color "bg+/n"
        @ 13,01 say "лл        " color "bg+/n"
        @ 14,01 say "лл      лл" color "bg+/n"
        @ 15,01 say "лллллллллп" color "bg+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "млллллллллм" color "bg+/n"
        @ 09,01 say "ллл      лл" color "bg+/n"
        @ 10,01 say "ллл        " color "bg+/n"
        @ 11,01 say "ллл        " color "bg+/n"
        @ 12,01 say "ллл        " color "bg+/n"
        @ 13,01 say "ллл        " color "bg+/n"
        @ 14,01 say "ллл      лл" color "bg+/n"
        @ 15,01 say "плллллллллп" color "bg+/n"

        for ncol := 1 to 80
                @ 08,ncol say "млллллллллм" color "bg+/n"
                @ 09,ncol say "ллл      лл" color "bg+/n"
                @ 10,ncol say "ллл        " color "bg+/n"
                @ 11,ncol say "ллл        " color "bg+/n"
                @ 12,ncol say "ллл        " color "bg+/n"
                @ 13,ncol say "ллл        " color "bg+/n"
                @ 14,ncol say "ллл      лл" color "bg+/n"
                @ 15,ncol say "плллллллллп" color "bg+/n"

                for nctr := 1 to 10000
                next

                restscreen(08,ncol,15,ncol,asaver)

        next

** end of letter c **


** display letter m **

        @ 08,01 say "л" color "r+/n"
        @ 09,01 say " " color "r+/n"
        @ 10,01 say " " color "r+/n"
        @ 11,01 say " " color "r+/n"
        @ 12,01 say " " color "r+/n"
        @ 13,01 say " " color "r+/n"
        @ 14,01 say " " color "r+/n"
        @ 15,01 say "л" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лл" color "r+/n"
        @ 09,01 say "л " color "r+/n"
        @ 10,01 say "л " color "r+/n"
        @ 11,01 say "л " color "r+/n"
        @ 12,01 say "л " color "r+/n"
        @ 13,01 say "л " color "r+/n"
        @ 14,01 say "л " color "r+/n"
        @ 15,01 say "лл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллл" color "r+/n"
        @ 09,01 say "лл " color "r+/n"
        @ 10,01 say "лл " color "r+/n"
        @ 11,01 say "лл " color "r+/n"
        @ 12,01 say "лл " color "r+/n"
        @ 13,01 say "лл " color "r+/n"
        @ 14,01 say "лл " color "r+/n"
        @ 15,01 say "ллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллл" color "r+/n"
        @ 09,01 say "ллл " color "r+/n"
        @ 10,01 say "ллл " color "r+/n"
        @ 11,01 say "ллл " color "r+/n"
        @ 12,01 say "ллл " color "r+/n"
        @ 13,01 say "ллл " color "r+/n"
        @ 14,01 say "ллл " color "r+/n"
        @ 15,01 say "лллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллл" color "r+/n"
        @ 09,01 say "лллл " color "r+/n"
        @ 10,01 say "пллл " color "r+/n"
        @ 11,01 say " ллл " color "r+/n"
        @ 12,01 say " ллл " color "r+/n"
        @ 13,01 say " ллл " color "r+/n"
        @ 14,01 say " ллл " color "r+/n"
        @ 15,01 say "ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллл" color "r+/n"
        @ 09,01 say "ллллл " color "r+/n"
        @ 10,01 say "лпллл " color "r+/n"
        @ 11,01 say "  ллл " color "r+/n"
        @ 12,01 say "  ллл " color "r+/n"
        @ 13,01 say "  ллл " color "r+/n"
        @ 14,01 say "  ллл " color "r+/n"
        @ 15,01 say " ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say " лллллл" color "r+/n"
        @ 09,01 say "оллллл " color "r+/n"
        @ 10,01 say "ллпллл " color "r+/n"
        @ 11,01 say "п  ллл " color "r+/n"
        @ 12,01 say "   ллл " color "r+/n"
        @ 13,01 say "   ллл " color "r+/n"
        @ 14,01 say "   ллл " color "r+/n"
        @ 15,01 say "  ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "  лллллл" color "r+/n"
        @ 09,01 say " оллллл " color "r+/n"
        @ 10,01 say "оллпллл " color "r+/n"
        @ 11,01 say "лп  ллл " color "r+/n"
        @ 12,01 say "    ллл " color "r+/n"
        @ 13,01 say "    ллл " color "r+/n"
        @ 14,01 say "    ллл " color "r+/n"
        @ 15,01 say "   ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "   лллллл" color "r+/n"
        @ 09,01 say "  оллллл " color "r+/n"
        @ 10,01 say "ноллпллл " color "r+/n"
        @ 11,01 say "ллп  ллл " color "r+/n"
        @ 12,01 say "     ллл " color "r+/n"
        @ 13,01 say "     ллл " color "r+/n"
        @ 14,01 say "     ллл " color "r+/n"
        @ 15,01 say "    ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "    лллллл" color "r+/n"
        @ 09,01 say "н  оллллл " color "r+/n"
        @ 10,01 say "лноллпллл " color "r+/n"
        @ 11,01 say "пллп  ллл " color "r+/n"
        @ 12,01 say "      ллл " color "r+/n"
        @ 13,01 say "      ллл " color "r+/n"
        @ 14,01 say "      ллл " color "r+/n"
        @ 15,01 say "     ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "л    лллллл" color "r+/n"
        @ 09,01 say "лн  оллллл " color "r+/n"
        @ 10,01 say "ллноллпллл " color "r+/n"
        @ 11,01 say " пллп  ллл " color "r+/n"
        @ 12,01 say "       ллл " color "r+/n"
        @ 13,01 say "       ллл " color "r+/n"
        @ 14,01 say "       ллл " color "r+/n"
        @ 15,01 say "      ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лл    лллллл" color "r+/n"
        @ 09,01 say "ллн  оллллл " color "r+/n"
        @ 10,01 say "пллноллпллл " color "r+/n"
        @ 11,01 say "  пллп  ллл " color "r+/n"
        @ 12,01 say "        ллл " color "r+/n"
        @ 13,01 say "        ллл " color "r+/n"
        @ 14,01 say "        ллл " color "r+/n"
        @ 15,01 say "л      ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллл    лллллл" color "r+/n"
        @ 09,01 say "лллн  оллллл " color "r+/n"
        @ 10,01 say "лпллноллпллл " color "r+/n"
        @ 11,01 say "л  пллп  ллл " color "r+/n"
        @ 12,01 say "л        ллл " color "r+/n"
        @ 13,01 say "л        ллл " color "r+/n"
        @ 14,01 say "л        ллл " color "r+/n"
        @ 15,01 say "лл      ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллл    лллллл" color "r+/n"
        @ 09,01 say "ллллн  оллллл " color "r+/n"
        @ 10,01 say "ллпллноллпллл " color "r+/n"
        @ 11,01 say "лл  пллп  ллл " color "r+/n"
        @ 12,01 say "лл        ллл " color "r+/n"
        @ 13,01 say "лл        ллл " color "r+/n"
        @ 14,01 say "лл        ллл " color "r+/n"
        @ 15,01 say "ллл      ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллл    лллллл" color "r+/n"
        @ 09,01 say "лллллн  оллллл " color "r+/n"
        @ 10,01 say "лллпллноллпллл " color "r+/n"
        @ 11,01 say "ллл  пллп  ллл " color "r+/n"
        @ 12,01 say "ллл        ллл " color "r+/n"
        @ 13,01 say "ллл        ллл " color "r+/n"
        @ 14,01 say "ллл        ллл " color "r+/n"
        @ 15,01 say "лллл      ллллл" color "r+/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллл    лллллл" color "r+/n"
        @ 09,01 say " лллллн  оллллл " color "r+/n"
        @ 10,01 say " лллпллноллпллл " color "r+/n"
        @ 11,01 say " ллл  пллп  ллл " color "r+/n"
        @ 12,01 say " ллл        ллл " color "r+/n"
        @ 13,01 say " ллл        ллл " color "r+/n"
        @ 14,01 say " ллл        ллл " color "r+/n"
        @ 15,01 say "ллллл      ллллл" color "r+/n"

        for ncol := 1 to 80
                @ 08,ncol say "лллллл    лллллл" color "r+/n"
                @ 09,ncol say " лллллн  оллллл " color "r+/n"
                @ 10,ncol say " лллпллноллпллл " color "r+/n"
                @ 11,ncol say " ллл  пллп  ллл " color "r+/n"
                @ 12,ncol say " ллл        ллл " color "r+/n"
                @ 13,ncol say " ллл        ллл " color "r+/n"
                @ 14,ncol say " ллл        ллл " color "r+/n"
                @ 15,ncol say "ллллл      ллллл" color "r+/n"

                for nctr := 1 to 10000
                next

                restscreen(08,ncol,15,ncol,asaver)
        next

** end of letter m **

** begin letter e **

        @ 08,01 say "л" color "b/n"
        @ 09,01 say "п" color "b/n"
        @ 10,01 say " " color "b/n"
        @ 11,01 say " " color "b/n"
        @ 12,01 say " " color "b/n"
        @ 13,01 say " " color "b/n"
        @ 14,01 say "м" color "b/n"
        @ 15,01 say "л" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лл" color "b/n"
        @ 09,01 say " п" color "b/n"
        @ 10,01 say "  " color "b/n"
        @ 11,01 say "  " color "b/n"
        @ 12,01 say "  " color "b/n"
        @ 13,01 say "  " color "b/n"
        @ 14,01 say " м" color "b/n"
        @ 15,01 say "лл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллл" color "b/n"
        @ 09,01 say "  п" color "b/n"
        @ 10,01 say "   " color "b/n"
        @ 11,01 say "   " color "b/n"
        @ 12,01 say "   " color "b/n"
        @ 13,01 say "   " color "b/n"
        @ 14,01 say "  м" color "b/n"
        @ 15,01 say "ллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллл" color "b/n"
        @ 09,01 say "   п" color "b/n"
        @ 10,01 say "    " color "b/n"
        @ 11,01 say "л   " color "b/n"
        @ 12,01 say "    " color "b/n"
        @ 13,01 say "    " color "b/n"
        @ 14,01 say "   м" color "b/n"
        @ 15,01 say "лллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллл" color "b/n"
        @ 09,01 say "    п" color "b/n"
        @ 10,01 say "     " color "b/n"
        @ 11,01 say "лл   " color "b/n"
        @ 12,01 say "     " color "b/n"
        @ 13,01 say "     " color "b/n"
        @ 14,01 say "    м" color "b/n"
        @ 15,01 say "ллллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллл" color "b/n"
        @ 09,01 say "     п" color "b/n"
        @ 10,01 say "      " color "b/n"
        @ 11,01 say "ллл   " color "b/n"
        @ 12,01 say "      " color "b/n"
        @ 13,01 say "      " color "b/n"
        @ 14,01 say "     м" color "b/n"
        @ 15,01 say "лллллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллл" color "b/n"
        @ 09,01 say "      п" color "b/n"
        @ 10,01 say "       " color "b/n"
        @ 11,01 say "лллл   " color "b/n"
        @ 12,01 say "       " color "b/n"
        @ 13,01 say "       " color "b/n"
        @ 14,01 say "      м" color "b/n"
        @ 15,01 say "ллллллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллл" color "b/n"
        @ 09,01 say "л      п" color "b/n"
        @ 10,01 say "л       " color "b/n"
        @ 11,01 say "ллллл   " color "b/n"
        @ 12,01 say "л       " color "b/n"
        @ 13,01 say "л       " color "b/n"
        @ 14,01 say "л      м" color "b/n"
        @ 15,01 say "лллллллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллллл" color "b/n"
        @ 09,01 say "лл      п" color "b/n"
        @ 10,01 say "лл       " color "b/n"
        @ 11,01 say "лллллл   " color "b/n"
        @ 12,01 say "лл       " color "b/n"
        @ 13,01 say "лл       " color "b/n"
        @ 14,01 say "лл      м" color "b/n"
        @ 15,01 say "ллллллллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллллл" color "b/n"
        @ 09,01 say "ллл      п" color "b/n"
        @ 10,01 say "ллл       " color "b/n"
        @ 11,01 say "ллллллл   " color "b/n"
        @ 12,01 say "ллл       " color "b/n"
        @ 13,01 say "ллл       " color "b/n"
        @ 14,01 say "ллл      м" color "b/n"
        @ 15,01 say "лллллллллл" color "b/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллллллл" color "b/n"
        @ 09,01 say " ллл      п" color "b/n"
        @ 10,01 say " ллл       " color "b/n"
        @ 11,01 say " ллллллл   " color "b/n"
        @ 12,01 say " ллл       " color "b/n"
        @ 13,01 say " ллл       " color "b/n"
        @ 14,01 say " ллл      м" color "b/n"
        @ 15,01 say "ллллллллллл" color "b/n"

        for ncol := 1 to 80
                @ 08,ncol say "ллллллллллл" color "b/n"
                @ 09,ncol say " ллл      п" color "b/n"
                @ 10,ncol say " ллл       " color "b/n"
                @ 11,ncol say " ллллллл   " color "b/n"
                @ 12,ncol say " ллл       " color "b/n"
                @ 13,ncol say " ллл       " color "b/n"
                @ 14,ncol say " ллл      м" color "b/n"
                @ 15,ncol say "ллллллллллл" color "b/n"

                for nctr := 1 to 10000
                next

                restscreen(08,ncol,15,ncol,asaver)
        next

** end of letter e **

** begin letter t **

        @ 08,01 say "л" color "g/n"
        @ 09,01 say "п" color "g/n"
        @ 10,01 say " " color "g/n"
        @ 11,01 say " " color "g/n"
        @ 12,01 say " " color "g/n"
        @ 13,01 say " " color "g/n"
        @ 14,01 say " " color "g/n"
        @ 15,01 say " " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лл" color "g/n"
        @ 09,01 say " п" color "g/n"
        @ 10,01 say "  " color "g/n"
        @ 11,01 say "  " color "g/n"
        @ 12,01 say "  " color "g/n"
        @ 13,01 say "  " color "g/n"
        @ 14,01 say "  " color "g/n"
        @ 15,01 say "  " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллл" color "g/n"
        @ 09,01 say "  п" color "g/n"
        @ 10,01 say "   " color "g/n"
        @ 11,01 say "   " color "g/n"
        @ 12,01 say "   " color "g/n"
        @ 13,01 say "   " color "g/n"
        @ 14,01 say "   " color "g/n"
        @ 15,01 say "   " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллл" color "g/n"
        @ 09,01 say "   п" color "g/n"
        @ 10,01 say "    " color "g/n"
        @ 11,01 say "    " color "g/n"
        @ 12,01 say "    " color "g/n"
        @ 13,01 say "    " color "g/n"
        @ 14,01 say "    " color "g/n"
        @ 15,01 say "    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллл" color "g/n"
        @ 09,01 say "    п" color "g/n"
        @ 10,01 say "     " color "g/n"
        @ 11,01 say "     " color "g/n"
        @ 12,01 say "     " color "g/n"
        @ 13,01 say "     " color "g/n"
        @ 14,01 say "     " color "g/n"
        @ 15,01 say "л    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллл" color "g/n"
        @ 09,01 say "л    п" color "g/n"
        @ 10,01 say "л     " color "g/n"
        @ 11,01 say "л     " color "g/n"
        @ 12,01 say "л     " color "g/n"
        @ 13,01 say "л     " color "g/n"
        @ 14,01 say "л     " color "g/n"
        @ 15,01 say "лл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллл" color "g/n"
        @ 09,01 say "лл    п" color "g/n"
        @ 10,01 say "лл     " color "g/n"
        @ 11,01 say "лл     " color "g/n"
        @ 12,01 say "лл     " color "g/n"
        @ 13,01 say "лл     " color "g/n"
        @ 14,01 say "лл     " color "g/n"
        @ 15,01 say "ллл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллл" color "g/n"
        @ 09,01 say "ллл    п" color "g/n"
        @ 10,01 say "ллл     " color "g/n"
        @ 11,01 say "ллл     " color "g/n"
        @ 12,01 say "ллл     " color "g/n"
        @ 13,01 say "ллл     " color "g/n"
        @ 14,01 say "ллл     " color "g/n"
        @ 15,01 say "лллл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллллл" color "g/n"
        @ 09,01 say " ллл    п" color "g/n"
        @ 10,01 say " ллл     " color "g/n"
        @ 11,01 say " ллл     " color "g/n"
        @ 12,01 say " ллл     " color "g/n"
        @ 13,01 say " ллл     " color "g/n"
        @ 14,01 say " ллл     " color "g/n"
        @ 15,01 say "ллллл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллллл" color "g/n"
        @ 09,01 say "  ллл    п" color "g/n"
        @ 10,01 say "  ллл     " color "g/n"
        @ 11,01 say "  ллл     " color "g/n"
        @ 12,01 say "  ллл     " color "g/n"
        @ 13,01 say "  ллл     " color "g/n"
        @ 14,01 say "  ллл     " color "g/n"
        @ 15,01 say " ллллл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллллллл" color "g/n"
        @ 09,01 say "   ллл    п" color "g/n"
        @ 10,01 say "   ллл     " color "g/n"
        @ 11,01 say "   ллл     " color "g/n"
        @ 12,01 say "   ллл     " color "g/n"
        @ 13,01 say "   ллл     " color "g/n"
        @ 14,01 say "   ллл     " color "g/n"
        @ 15,01 say "  ллллл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "лллллллллллл" color "g/n"
        @ 09,01 say "    ллл    п" color "g/n"
        @ 10,01 say "    ллл     " color "g/n"
        @ 11,01 say "    ллл     " color "g/n"
        @ 12,01 say "    ллл     " color "g/n"
        @ 13,01 say "    ллл     " color "g/n"
        @ 14,01 say "    ллл     " color "g/n"
        @ 15,01 say "   ллллл    " color "g/n"

        for nctr := 1 to 10000
        next

        @ 08,01 say "ллллллллллллл" color "g/n"
        @ 09,01 say "п    ллл    п" color "g/n"
        @ 10,01 say "     ллл     " color "g/n"
        @ 11,01 say "     ллл     " color "g/n"
        @ 12,01 say "     ллл     " color "g/n"
        @ 13,01 say "     ллл     " color "g/n"
        @ 14,01 say "     ллл     " color "g/n"
        @ 15,01 say "    ллллл    " color "g/n"

        for ncol := 1 to 80
                @ 08,ncol say "ллллллллллллл" color "g/n"
                @ 09,ncol say "п    ллл    п" color "g/n"
                @ 10,ncol say "     ллл     " color "g/n"
                @ 11,ncol say "     ллл     " color "g/n"
                @ 12,ncol say "     ллл     " color "g/n"
                @ 13,ncol say "     ллл     " color "g/n"
                @ 14,ncol say "     ллл     " color "g/n"
                @ 15,ncol say "    ллллл    " color "g/n"

                for nctr := 1 to 10000
                next

                restscreen(08,ncol,15,ncol,asaver)
        next

** end of letter t **
wait
return nil
